
stages:          # List of stages for jobs, and their order of execution
  - install_tools
  - test
  - security

install_mvn_trivy_docker_kubectl:       # This job runs in the build stage, which runs first.
  stage: install_tools
  script:
    - mvn --version
    - java --version
    - trivy version
    - docker version
  tags:
    - self-hosted

unit_testing:
  stage: test
  script:
    - mvn test
  tags:
    - self-hosted

trivy_fs_scan:
  stage: security
  script:
    - trivy fs --format table -D fileSystem.html .
  tags:
    - self-hosted


