
stages:          # List of stages for jobs, and their order of execution
  - install_tools
  - test

install_mvn_trivy_docker_kubectl:       # This job runs in the build stage, which runs first.
  stage: install_tools
  script:
    - mvn --version
    - java --version
    - trivy version
    - docker version
    - sudo snap install kubectl --classic
  tags:
    - self-hosted

unit_testing:
  stage: test
  script:
    - mvn test
  tags:
    - self-hosted


